version: '3'

services:
  bot:
    depends_on:
      - rabbitmq
      - celery-worker
      - redis
    image: benyomin/bib_bot
    ports:
      - "8000:8443"
    env_file: .env
    working_dir: /home/code
    command: >
      bash -c "git clone https://github.com/benyomin94/israel_bus_info_bot.git /home/code &&
               pip install -r requirements.txt &&
               python bot.py"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "8100:15672"
    env_file: .env

  redis:
    image: redis

  celery-worker:
    depends_on:
      - rabbitmq
      - redis
    image: benyomin/bib_celery
    env_file: .env
    working_dir: /home/code
    command: >
      bash -c "git clone https://github.com/benyomin94/israel_bus_info_bot.git /home/code &&
               celery -A tasks beat -l warning"

  celery-beat:
    depends_on:
      - rabbitmq
    image: benyomin/bib_celery
    env_file: .env
    working_dir: /home/code
    command: >
      bash -c "git clone https://github.com/benyomin94/israel_bus_info_bot.git /home/code &&
               celery -A tasks worker -l warning --concurrency=2"