version: '3'

services:
  bot:
    depends_on:
      - rabbitmq
      - celery-worker
      - redis
    build:
      context: ./docker
      dockerfile: Dockerfile_bot
    ports:
      - "8000:8443"
    env_file: .env

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "8100:15672"
    env_file: .env

  redis:
    image: redis

  celery-worker:
    depends_on:
      - rabbitmq
      - redis
    build:
      context: ./docker
      dockerfile: Dockerfile_celery_worker
    env_file: .env

  celery-beat:
    depends_on:
      - rabbitmq
    build:
      context: ./docker
      dockerfile: celery_beat
    env_file: .env